CREATE TABLE IF NOT EXISTS Receipt (
    id VARCHAR(100) NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Item (
    receiptid VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    cost INTEGER,
    FOREIGN KEY(receiptid) REFERENCES Receipt(id) ON DELETE CASCADE ON UPDATE CASCADE
);
